CREATE TABLE [Client] (
    [ClientID] smallint NOT NULL,
    [SystemDepartmentID] smallint NULL,
    [RegionID] smallint NULL,
    [ClientCode] nvarchar(10) NULL,
    [Name] nvarchar(50) NOT NULL,
    [Address] nvarchar(200) NULL,
    [FirstPhone] nvarchar(13) NULL,
    [SecondPhone] nvarchar(20) NULL,
    [Mobile] nvarchar(13) NULL,
    [Fax] nvarchar(13) NULL,
    [SalesPersonID] smallint NULL,
    [Email] nvarchar(50) NULL,
    [Country] nvarchar(20) NULL,
    [ClientLimit] float NULL,
    [Begining Balance] decimal NULL,
    [ClientBalance] float NULL,
    [Discount] float NULL,
    [CurrencyID] smallint NULL,
    [ContactPerson] nvarchar(200) NULL,
    [AccountNo] nvarchar(50) NULL,
    [Active] tinyint NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL,
    CONSTRAINT [PK_Client] PRIMARY KEY ([ClientID])
);
