CREATE TABLE [ClientOrder] (
    [ClientOrderID] int NOT NULL,
    [RequestNo] varchar(12) NULL,
    [ClientID] smallint NOT NULL,
    [StoreID] smallint NOT NULL,
    [SalesPersonID] smallint NULL,
    [Trans_Year] int NULL,
    [Serial] int NULL,
    [NoteSerial] nvarchar(20) NULL,
    [CurrencyID] int NULL,
    [Rate] decimal NULL,
    [TotalPrice] decimal NULL,
    [DiscountAmount] decimal NULL,
    [TotalDiscount] decimal NULL,
    [TaxPercentage] decimal NULL,
    [TaxAmount] decimal NULL,
    [NetPrice] decimal NULL,
    [PayedAmount] decimal NULL,
    [OrderDate] smalldatetime NOT NULL,
    [DeliveryDate] smalldatetime NULL,
    [FinishDate] smalldatetime NOT NULL,
    [Paid] tinyint NULL,
    [Status] tinyint NOT NULL,
    [HasInvoice] smallint NULL,
    [Comment] nvarchar(200) NULL,
    [SpecialOffers] bit NULL,
    [SpecialOfferID] int NULL,
    [SpecialOfferNo] int NULL,
    [PaymentType] int NULL,
    [Posted] bit NULL,
    [Canceled] bit NULL,
    [TotalSaleDiscount] decimal NULL,
    [EmployeeID] smallint NULL,
    CONSTRAINT [PK_ClientOrder] PRIMARY KEY ([ClientOrderID])
);
