CREATE TABLE [Customer] (
    [CustomerID] int NOT NULL,
    [CustomerType] tinyint NULL,
    [Active] smallint NULL,
    [CustomerName] nvarchar(100) NOT NULL,
    [Phones] nvarchar(100) NULL,
    [Phone2] nvarchar(100) NULL,
    [Address] nvarchar(100) NULL,
    [Email] varchar(100) NULL,
    [Mobile] nvarchar(20) NULL,
    [Fax] nvarchar(50) NULL,
    [ContactPerson] nvarchar(100) NULL,
    [BeginingBalance] decimal NULL,
    [Balance] decimal NOT NULL,
    [GenderID] smallint NULL,
    [AgeGroupID] smallint NULL,
    [CountryID] smallint NULL,
    [ClassID] smallint NULL,
    [DiscountCardNumber] nvarchar(200) NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL,
    [CreateGalleryID] smallint NULL,
    [CustomerCode] nvarchar(10) NULL,
    [PD] nvarchar(10) NULL,
    [R.Sph.Dist.] nvarchar(10) NULL,
    [R.Sph.Read] nvarchar(10) NULL,
    [R.Sph.CLens] nvarchar(10) NULL,
    [R.Cyl.Dist.] nvarchar(10) NULL,
    [R.Cyl.Read] nvarchar(10) NULL,
    [R.Cyl.CLens] nvarchar(10) NULL,
    [R.Ax.Dist.] nvarchar(10) NULL,
    [R.Ax.Read] nvarchar(10) NULL,
    [R.Ax.CLens] nvarchar(10) NULL,
    [L.Sph.Dist.] nvarchar(10) NULL,
    [L.Sph.Read] nvarchar(10) NULL,
    [L.Sph.CLens] nvarchar(10) NULL,
    [L.Cyl.Dist.] nvarchar(10) NULL,
    [L.Cyl.Read] nvarchar(10) NULL,
    [L.Cyl.CLens] nvarchar(10) NULL,
    [L.Ax.Dist.] nvarchar(10) NULL,
    [L.Ax.Read] nvarchar(10) NULL,
    [L.Ax.CLens] nvarchar(10) NULL,
    [CheckDate] datetime NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY ([CustomerID])
);
