CREATE TABLE [CustomerOrder] (
    [CustomerOrderID] int NOT NULL,
    [Trans_Year] int NULL,
    [Serial] int NULL,
    [GalleryID] smallint NULL,
    [EmployeeID] smallint NOT NULL,
    [PaymentType] nvarchar(12) NULL,
    [CreditCardID] smallint NULL,
    [NoteSerial] nvarchar(20) NULL,
    [ReceiptNo] int NOT NULL,
    [Paid] smallint NOT NULL,
    [Printed] tinyint NULL,
    [OrderDate] smalldatetime NOT NULL,
    [TotalPriceBeforeDiscount] decimal NULL,
    [TotalPrice] decimal NOT NULL,
    [CashAmount] decimal NOT NULL,
    [CouponAMount] decimal NULL,
    [CreditAmount] decimal NOT NULL,
    [DiscountAmount] decimal NOT NULL,
    [RevokeAmount] decimal NOT NULL,
    [TotalDiscount] decimal NOT NULL,
    [CardNumber] varchar(20) NULL,
    [PatchNumber] varchar(50) NULL,
    [Excluded] char(1) NULL,
    [CustomerID] int NULL,
    [InsuranceCompanyId] smallint NULL,
    [CreatedBy] smallint NULL,
    [CustomerOrderMasterID] varchar(25) NULL,
    [DownPaymentID] int NULL,
    [SpecialOffers] bit NULL,
    [SpecialOfferID] int NULL,
    [NoOfSpecialOffers] int NULL,
    [dtFinishDate] datetime NULL,
    [Comment] nvarchar(4000) NULL,
    [Posted] bit NULL,
    [Canceled] bit NULL,
    [InsuredNo] nvarchar(20) NULL,
    [InsuranceDiscount] decimal NULL,
    [Deductible] decimal NULL,
    [approveamount] decimal NULL,
    [TransNo] nvarchar(20) NULL,
    [insurranceCustomerName] nvarchar(200) NULL,
    [InsurranceCustomerMobile] nvarchar(50) NULL,
    [PolicyNo] nvarchar(50) NULL,
    [ApprovedNO] nvarchar(50) NULL,
    [ClaimDate] smalldatetime NULL,
    [OpTransfer] smallint NULL,
    [PolicyHolder] nvarchar(250) NULL,
    [subHolder] nvarchar(50) NULL,
    [IDeqama] nvarchar(50) NULL,
    CONSTRAINT [PK_CustomerOrder] PRIMARY KEY ([CustomerOrderID])
);
