CREATE TABLE [Gallery] (
    [GalleryID] smallint NOT NULL,
    [Name] nvarchar(50) NOT NULL,
    [Address] nvarchar(50) NULL,
    [Phones] nvarchar(50) NULL,
    [GalleryMasterID] smallint NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL,
    [CurrencyID] int NULL,
    [DiscountPercentage] decimal NULL,
    [RegionID] int NULL,
    [SystemDepartmentID] tinyint NULL,
    [Extension] varchar(10) NULL,
    [Responsible] nvarchar(50) NULL,
    [CashAccountNo] nvarchar(50) NULL,
    [CreditAccountNo] nvarchar(50) NULL,
    [RemainsAccountNo] nvarchar(50) NULL,
    [SalesAccountNo] nvarchar(50) NULL,
    [DownPaymentAccountNo] nvarchar(50) NULL,
    [BeginningBalance] decimal NULL,
    [Bankcommissions] nvarchar(50) NULL,
    [GalleryCode] nvarchar(50) NULL,
    CONSTRAINT [PK_Gallery] PRIMARY KEY ([GalleryID])
);
