CREATE TABLE [Product2_copy] (
    [ProductID] int NOT NULL,
    [Code] nvarchar(50) NOT NULL,
    [MainGroupID] smallint NULL,
    [CategoryID] smallint NULL,
    [SubCategoryID] smallint NULL,
    [Description] nvarchar(200) NULL,
    [FreeCode] nvarchar(20) NULL,
    [Lookup1Value] smallint NULL,
    [Lookup2Value] smallint NULL,
    [Lookup3Value] smallint NULL,
    [Lookup4Value] smallint NULL,
    [Lookup5Value] smallint NULL,
    [Lookup6Value] smallint NULL,
    [Status] tinyint NOT NULL,
    [GenderID] smallint NULL,
    [SeasonID] smallint NULL,
    [ManufacturerID] smallint NULL,
    [NewCode] varchar(50) NOT NULL,
    [OriginalCode] varchar(50) NULL,
    [MaestroCode] nvarchar(50) NULL,
    [ShipmentNo] int NULL,
    [Field1] nvarchar(100) NULL,
    [Field2] nvarchar(100) NULL,
    [Field3] nvarchar(100) NULL,
    [Field4] nvarchar(100) NULL,
    [Image] varchar(50) NULL,
    [HasExpiryDate] bit NULL,
    [StoreLimit] smallint NULL,
    [GalleryLimit] smallint NULL,
    [RetailPrice] decimal NULL,
    [GallerySaleDateFrom] smalldatetime NULL,
    [GallerySaleDateTo] smalldatetime NULL,
    [GalleryDiscount] decimal NULL,
    [GallerySaleDiscount] decimal NULL,
    [WhalePrice] decimal NULL,
    [StoreSaleDateFrom] smalldatetime NULL,
    [StoreSaleDateTo] smalldatetime NULL,
    [StoreDiscount] decimal NULL,
    [StoreSaleDiscount] decimal NULL,
    [TotalCost] decimal NULL,
    [TotalQuantity] decimal NULL,
    [CostPrice] decimal NULL,
    [EvaluationPrice] decimal NULL,
    [StoreLowerLimit] int NULL,
    [GalleryLowerLimit] int NULL,
    [StoreUpperLimit] int NULL,
    [GalleryUpperLimit] int NULL,
    [ReOrderLimit] int NULL,
    [RecessLimit] int NULL,
    [IsPresent] bit NULL,
    [CreationDate] smalldatetime NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL
);
