CREATE TABLE [StoreYearSerial] (
    [Year] int NOT NULL,
    [StoreID] smallint NOT NULL,
    [AdjustmentSerial] int NULL,
    [StoreRevokeSerial] int NULL,
    [GalleriesOrderSerial] int NULL,
    [GalleriesRevokeSerial] int NULL,
    [ClientRequestSerial] int NULL,
    [ClientOrderSerial] int NULL,
    [ClientRevokeSerial] int NULL,
    [ClientPaymentSerial] int NULL,
    [ClientRevokePayment] int NULL,
    [ClientAdjustmentSerial] int NULL,
    [PurchaseOrderSerial] int NULL,
    [SupplierInvoiceSerial] int NULL,
    [SupplierRevokeSerial] int NULL,
    [ExchangeProductsSerial] int NULL,
    [RequestProductSerial] int NULL,
    [TransferSerial] int NULL,
    [SpoiledProductsSerial] int NULL,
    [OpeningBalanceSerial] int NULL,
    [ProductTransferSerial] int NULL,
    CONSTRAINT [PK_StoreYearSerial] PRIMARY KEY ([StoreID], [Year])
);
