CREATE TABLE [Supplier] (
    [SupplierID] smallint NOT NULL,
    [SupplierCode] nvarchar(10) NULL,
    [SystemDepartmentID] smallint NULL,
    [Name] nvarchar(50) NOT NULL,
    [Address] nvarchar(50) NULL,
    [FirstPhone] nvarchar(13) NULL,
    [SecondPhone] nvarchar(13) NULL,
    [Email] nvarchar(50) NULL,
    [Fax] nvarchar(13) NULL,
    [Country] nvarchar(25) NULL,
    [Discount] float NULL,
    [Mobile] nvarchar(13) NULL,
    [intCurrencyID] tinyint NULL,
    [ContactPerson] nvarchar(200) NULL,
    [Active] tinyint NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL,
    [AccountNo] nvarchar(200) NULL,
    [BeginningBalance] decimal NULL,
    CONSTRAINT [PK_Supplier] PRIMARY KEY ([SupplierID])
);
