CREATE TABLE [SupplierRevoke] (
    [SupplierRevokeID] int NOT NULL,
    [StoreID] smallint NULL,
    [SupplierID] smallint NULL,
    [bitHasInvoice] bit NULL,
    [SupplierInvoiceID] int NULL,
    [Trans_Year] int NULL,
    [Serial] int NULL,
    [RevokeDate] datetime NULL,
    [Status] tinyint NULL,
    [SendReceipt] int NULL,
    [CurrencyRate] decimal NULL,
    [CurrencyID] decimal NULL,
    [TotalRevokeAmount] decimal NULL,
    [TotalRevokeBaseAmount] decimal NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL,
    [Posted] bit NULL,
    [dtPostDate] datetime NULL,
    [sinPostUserID] smallint NULL,
    [Canceled] bit NULL,
    [FreeSerial] bigint NULL,
    CONSTRAINT [PK_SupplierRevoke] PRIMARY KEY ([SupplierRevokeID])
);
