CREATE TABLE [SupplierInvoice] (
    [SupplierInvoiceID] int NOT NULL,
    [Serial] int NULL,
    [Trans_Year] int NULL,
    [StoreID] smallint NOT NULL,
    [OriginalInvoiceNo] nvarchar(50) NULL,
    [SupplierID] smallint NOT NULL,
    [EmployeeID] smallint NOT NULL,
    [InvoiceDate] smalldatetime NOT NULL,
    [Status] tinyint NOT NULL,
    [CurrencyRate] decimal NULL,
    [CurrencyID] int NULL,
    [TotalBasePrice] decimal NULL,
    [TotalPrice] decimal NULL,
    [TotalBaseDiscount] decimal NULL,
    [TotalDiscount] decimal NULL,
    [Posted] bit NOT NULL,
    [Canceled] bit NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL,
    [dtPostDate] datetime NULL,
    [sinPostUserID] smallint NULL,
    [FreeSerial] bigint NULL,
    CONSTRAINT [PK_SupplierInvoice] PRIMARY KEY ([SupplierInvoiceID])
);
