CREATE TABLE [SystemSettings] (
    [inID] int NOT NULL,
    [bolStoreOption] bit NULL,
    [bolAllowMinus] bit NULL,
    [bolEditPendingTransaction] bit NULL,
    [bolPhysicalDeleteTransaction] bit NULL,
    [bolPrintedSerial] bit NULL,
    [bolExcludeInvoices] bit NULL,
    [nExcludePeriod] int NULL,
    [bolLogin] bit NULL,
    [nLoginStart] int NULL,
    [nLoginEnd] int NULL,
    [nLoginStart_Shift2] int NULL,
    [nLoginEnd_Shift2] int NULL,
    [bolDeleteProcessedTransaction] bit NULL,
    [bolPrintPendingTransaction] bit NULL,
    [bolAllowBuiltInOppositeTransaction] bit NULL,
    [bolEditPrice] bit NULL,
    [bolEditSalesPerson] bit NULL,
    [bolIncludeTax] bit NULL,
    [bolpageSize] bit NULL,
    [nPageSize] int NULL,
    CONSTRAINT [PK_SystemSettings] PRIMARY KEY ([inID])
);
