CREATE TABLE [Transfer] (
    [TransferID] int NOT NULL,
    [EmployeeID] smallint NOT NULL,
    [Trans_Year] int NULL,
    [Serial] int NULL,
    [FreeSerial] bigint NULL,
    [TransferFrom] smallint NOT NULL,
    [TransferTypeFrom] smallint NULL,
    [TransferTo] smallint NOT NULL,
    [TransferTypeTo] smallint NULL,
    [TransferDate] smalldatetime NOT NULL,
    [DeliveryDate] smalldatetime NULL,
    [SendReceipt] int NULL,
    [ReceiveReceipt] int NULL,
    [Status] tinyint NOT NULL,
    [TotalQuantity] decimal NULL,
    [TotalValue] decimal NULL,
    [RequestProductID] int NULL,
    [dtCreateDate] datetime NULL,
    [sinCreateUserID] smallint NULL,
    [dtUpdateDate] datetime NULL,
    [sinUpdateUserID] smallint NULL,
    [Posted] bit NULL,
    [dtPostDate] datetime NULL,
    [sinPostUserID] smallint NULL,
    [PostRefrenceID] smallint NULL,
    [Canceled] bit NULL,
    [bolDeleted] bit NULL,
    [Comment] nvarchar(2000) NULL,
    CONSTRAINT [PK_Transfer] PRIMARY KEY ([TransferID])
);
